apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-first-kube
          image: kodega2016/first-kube
          ports:
            - containerPort: 8080
          livenessProbe:
            periodSeconds: 10
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 8080
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: first-deployment-node-port-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: deployment
      port: 8080
      targetPort: 8080
      protocol: TCP
